# Use postgres/example user/password credentials
version: '3.1'

services:
# https://hub.docker.com/_/postgres
# https://github.com/cookiecutter/cookiecutter-django
# https://cookiecutter-django.readthedocs.io/en/latest/developing-locally-docker.html
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: django-api-rest_production_postgres
    container_name: django-api-rest_local_postgres
    env_file:
      - ./.envs/.local/.postgres
    volumes:
      - django_api-rest:/var/lib/postgresql/data
      # - djangobasepro_data_backups:/backups
    ports:
      - 5434:5432
      # puerto de mi maquina : puerto de docker
volumes:
  django_api-rest:
  # djangobasepro_data_backups: