# Generated by Django 5.0.1 on 2024-01-31 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(choices=[('COCHE', 'Coche'), ('CICLO', 'Ciclomotor'), ('MOTO', 'Motocicleta')], max_length=20)),
                ('chasis', models.CharField(max_length=50, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(choices=[('ROJO', 'Rojo'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('NEGRO', 'Negro'), ('GRIS', 'Gris'), ('BLANCO', 'Blanco'), ('OTRO', 'Otro')], max_length=20)),
                ('fecha_fabricacion', models.DateField()),
                ('fecha_matriculacion', models.DateField()),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('suspendido', models.BooleanField(default=False)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehiculos.marca')),
            ],
            options={
                'verbose_name_plural': 'Vehiculos',
            },
        ),
    ]
