# Generated by Django 5.0.2 on 2024-02-12 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patinete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Tipo 1', 'Tipo 1'), ('Tipo 2', 'Tipo 2'), ('Tipo 3', 'Tipo 3')], max_length=50)),
                ('precio_desbloqueo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_minuto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desbloqueo', models.DateTimeField()),
                ('fecha_entrega', models.DateTimeField()),
                ('coste_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('patinete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patinetes.patinete')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patinetes.usuario')),
            ],
        ),
    ]
